networks:
  Conv_net:
    name: network

services:
  frontend:
    container_name: server
    build:
      context: ./frontend
    networks:
        - Conv_net
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - .env
    networks:
        - Conv_net
  database:
    image: postgres:14-alpine
    env_file:
      .env 
    networks:
        - Conv_net
    restart: always
